version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_UPLOAD_URL=http://localhost:5001
      - REACT_APP_AI_URL=http://localhost:5002
    depends_on:
      - upload-service
      - ai-service

  upload-service:
    build: ./upload-service
    ports:
      - "5001:5001"
    environment:
      - AI_SERVICE_URL=http://ai-service:5002
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "5002:5002"
    env_file:
      - ./ai-service/.env
